---
- name: install nad start the serive 
  hosts: all
  become: yes
  vars:
    - apps: [nginx,python3,vim]
  tasks: 
  - name: Installing nginix
    yum:
      name: "{{ item }}"
      state: present
    tags: i-nginx
    with_items: "{{apps}}"
