---
- name: set password of user
  hosts: all
  become: yes
  
  tasks:
    - name: set password
      user:
        name: nayan
        update_password: always
        password: "{{'nayan123' | password_hash('sha512')}}"
