---
# tasks file for httpd_setup
- name: install htppd
  yum:
    name: "{{ httpd_package_name }}"
    state: present
  become: true
- name: place html file
  copy:
    src: index.html 
    dest: /var/www/html/index.html
  become: true
- name: Start the service
  service:
    name: "{{ httpd_package_name }}"
    state: started
    enabled: yes
  become: true
    
